version: '3.7'

services: 
    user-db:
        image: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: todo
        ports: 
            - "5432:5432"
